### ISSUE TITLE
Brief overview of 'anyOf' coding challenges?

### ISSUE THREAD

**Issue by sixman9** [VoxSupplyChain/json-schema-codegen#2]
Hi,
Basically, I have a [JSON Schema file][jsonld-schema] which includes an '**anyOf**' block. As your README states* 'anyOf' isn't supported (*among others). Could you, briefly, explain any of the coding issues regarding its potential implementation and inclusion?

If it's not too difficult, I might lend myself to making the project at least compatible with my target Schema ([JSON-LD schema][jsonld-schema]).

Thanks

Rich

[jsonld-schema]: https://github.com/json-ld/json-ld.org/blob/master/schemas/jsonld-schema.json

**Comment by tptodorov** [comment]
Hi Rich,

JSON Schema is a set of validation rules. Most of the rules are simple enough to guess what corresponding Scala representation should be, but "allof", anyof, oneof can not be mapped to meaningful Scala type.  How would you represent them in Scala?
OneOf could be represented as Either[A,B,C....] if we had such a type. 

In our case, since all our schemas are defined by us, we can go around these problems by not using "*Of" rules.

I don't think you can use it with JSON-LD schema. In fact, as defined, JSON-LD is very hard to map to a strong typed representation (e.g "type": ["object", "array"] is a problem too)

Good luck,
Todor
